# Numpy
NumPy stands for Numerical Python and is one of the most useful scientific libraries in Python programming. It provides support for large multidimensional array objects and various tools to work with them. 

# What is an Array?
Arrays are a collection of elements/values, that can have one or more dimensions. An array of one dimension is called a Vector while having two dimensions is called a Matrix.

NumPy arrays are called ndarray or N-dimensional arrays and they store elements of the same type and size. It is known for its high-performance and provides efficient storage and data operations as arrays grow in size.

# Lists vs Array
A Python object is actually a pointer to a memory location that stores all the details about the object, like bytes and the value. Although this extra information is what makes Python a dynamically typed language, it also comes at a cost which becomes apparent when storing a large collection of objects, like in an array.

Python lists are essentially an array of pointers, each pointing to a location that contains the information related to the element. This adds a lot of overhead in terms of memory and computation. And most of this information is rendered redundant when all the objects stored in the list are of the same type!

To overcome this problem, we use NumPy arrays that contain only homogeneous elements, i.e. elements having the same data type. This makes it more efficient at storing and manipulating the array. This difference becomes apparent when the array has a large number of elements, say thousands or millions. Also, with NumPy arrays, you can perform element-wise operations, something which is not possible using Python lists!

This is the reason why NumPy arrays are preferred over Python lists when performing mathematical operations on a large amount of data.

In [12]:
import numpy as np #as keyword is used to create an alias.

# Making arrays
`np.array()`is used to make an array.

In [2]:
np.array([1,2,3,4]) #creating a basic array (one dimensional)

array([1, 2, 3, 4])

In [10]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [11]:
arr

array([1, 2, 3, 4, 5])

In [3]:
np.array([1,2,3,4],dtype=np.float64) #we can specify data type in dtype

array([1., 2., 3., 4.])

A matrix is just a rectangular array of numbers with shape N x M where N is the number of rows and M is the number of columns in the matrix.

In [4]:
np.array([[1,2,3,4],[5,6,7,8]]) # multi dimensional array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]  

arr=np.array([my_lst1,my_lst2,my_lst3]) # making multi dimensional array


In [15]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [13]:
type(arr)

numpy.ndarray

# Array of Zeroes
NumPy lets you create an array of all zeros using the `np.zeros()` method. All you have to do is pass the shape of the desired array.

In [18]:
np.zeros(5) # np.zeroes() uses to make an array of zeroes

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,3)) #two dimensional zeroes array

array([[0., 0., 0.],
       [0., 0., 0.]])

# Array of Ones

In [20]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1])

In [23]:
np.ones((2,3)) #multidimensional array

array([[1., 1., 1.],
       [1., 1., 1.]])

# Random  numbers in array (random distribution)

In [24]:
np.random.rand(2,3)


array([[0.73754641, 0.44129706, 0.82475495],
       [0.88458366, 0.43307417, 0.53462493]])

# An array of your choice
Create an array filled with any given value using the `np.full()` method. Just pass in the shape of the desired array and the value you want:

In [25]:
np.full((2,2),(6,7))

array([[6, 7],
       [6, 7]])

In [26]:
np.full((2,2),6)

array([[6, 6],
       [6, 6]])

# Identity Matrix
An Identity matrix is a square matrix that has 1s along its main diagonal and 0s everywhere else.

[np.eye()](https://numpy.org/doc/stable/reference/generated/numpy.eye.html) returns an array with 1s along its diagonal and 0s everywhere else.
A square matrix has an N x N shape. This means it has the same number of rows and columns.

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

NumPy gives you the flexibility to change the diagonal along which the values have to be 1s. You can either move it above the main diagonal

Note: A matrix is called the Identity matrix only when the 1s are along the main diagonal and not any other diagonal!

In [29]:
np.eye(3,k=-2) #moving below main diagonal

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [30]:
np.eye(3,k=1) #moving above main diagonal

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

# Evenly spaced ndarray
You can quickly get an evenly spaced array of numbers using the `np.arange()` method:

In [31]:
np.arange(5)

array([0, 1, 2, 3, 4])

The start, end and step size of the interval of values can be explicitly defined by passing in three numbers as arguments for these values respectively. A point to be noted here is that the interval is defined as [start,end)  where the last number will not be included in the array:

In [33]:
np.arange(2,10,2)

array([2, 4, 6, 8])

Another similar function is `np.linspace()`, but instead of step size, it takes in the number of samples that need to be retrieved from the interval. A point to note here is that the last number is included in the values returned unlike in the case of np.arange().

In [34]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Dimensions of NumPy arrays

In [38]:
# number of axis
a = np.array([[4,3,10],[12,23,20]])


In [37]:
print('Array :','\n',a)
print('Dimensions :','\n',a.ndim)

Array : 
 [[ 4  3 10]
 [12 23 20]]
Dimensions : 
 2


This array has two dimensions: 2 rows and 3 columns.

# Shape of NumPy array
The shape is an attribute of the NumPy array that shows how many rows of elements are there along each dimension. You can further index the shape so returned by the ndarray to get value along each dimension:

In [39]:
a = np.array([[1,2,3],[4,5,6]])
print('Array :','\n',a)


Array : 
 [[1 2 3]
 [4 5 6]]


In [40]:
print('Shape :','\n',a.shape)


Shape : 
 (2, 3)


In [41]:
print('Rows = ',a.shape[0])

Rows =  2


In [42]:
print('Columns = ',a.shape[1])

Columns =  3


# Size of NumPy array
You can determine how many values there are in the array using the size attribute. It just multiplies the number of rows by the number of columns in the ndarray:



In [43]:
# size of array
a = np.array([[5,10,15],[20,25,20]])
print('Size of array :',a.size)

Size of array : 6


# Reshaping a NumPy array
Reshaping a ndarray can be done using the np.reshape() method. It changes the shape of the ndarray without changing the data within the ndarray:

In [44]:
# reshape
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

Here, I reshaped the ndarray from a 1-D to a 2-D ndarray.

While reshaping, if you are unsure about the shape of any of the axis, just input -1. NumPy automatically calculates the shape when it sees a -1:

In [45]:
a = np.array([3,6,9,12,18,24])
print('Three rows :','\n',np.reshape(a,(3,-1)))


Three rows : 
 [[ 3  6]
 [ 9 12]
 [18 24]]


In [46]:
print('Three columns :','\n',np.reshape(a,(-1,3)))

Three columns : 
 [[ 3  6  9]
 [12 18 24]]


In [72]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [73]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.arange(0,10).reshape(2,5)

In [74]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

# Flattening a NumPy array
Sometimes when you have a multidimensional array and want to collapse it to a single-dimensional array, you can either use the flatten() method or the ravel() method:

In [47]:
a = np.ones((2,2))
b = a.flatten()
c = a.ravel()

In [48]:
print('Original shape :', a.shape)
print('Array :','\n', a)


Original shape : (2, 2)
Array : 
 [[1. 1.]
 [1. 1.]]


In [49]:
print('Shape after flatten :',b.shape)
print('Array :','\n', b)


Shape after flatten : (4,)
Array : 
 [1. 1. 1. 1.]


In [50]:
print('Shape after ravel :',c.shape)
print('Array :','\n', c)

Shape after ravel : (4,)
Array : 
 [1. 1. 1. 1.]


But an important difference between flatten() and ravel() is that the former returns a copy of the original array while the latter returns a reference to the original array. `This means any changes made to the array returned from ravel() will also be reflected in the original array while this will not be the case with flatten().`

In [51]:
b[0] = 0
print(a)

[[1. 1.]
 [1. 1.]]


The change made was not reflected in the original array.

In [52]:
c[0] = 0
print(a)

[[0. 1.]
 [1. 1.]]


But here, the changed value is also reflected in the original ndarray.

### What is happening here is that flatten() creates a Deep copy of the ndarray while ravel() creates a Shallow copy of the ndarray.

Deep copy means that a completely new ndarray is created in memory and the ndarray object returned by flatten() is now pointing to this memory location. Therefore, any changes made here will not be reflected in the original ndarray.

A Shallow copy, on the other hand, returns a reference to the original memory location. Meaning the object returned by ravel() is pointing to the same memory location as the original ndarray object. So, definitely, any changes made to this ndarray will also be reflected in the original ndarray too.
![copy](https://cdn.analyticsvidhya.com/wp-content/uploads/2020/04/Shallow-deep-copy.png)

# Transpose of a NumPy array
Another very interesting reshaping method of NumPy is the transpose() method. It takes the input array and swaps the rows with the column values, and the column values with the values of the rows:

In [54]:
a = np.array([[1,2,3],
[4,5,6]])
b = np.transpose(a)


In [55]:
print('Original','\n','Shape',a.shape,'\n',a)


Original 
 Shape (2, 3) 
 [[1 2 3]
 [4 5 6]]


In [56]:
print('Expand along columns:','\n','Shape',b.shape,'\n',b)

Expand along columns: 
 Shape (3, 2) 
 [[1 4]
 [2 5]
 [3 6]]


# Expanding and Squeezing a NumPy array
## Expanding a NumPy array
You can add a new axis to an array using the expand_dims() method by providing the array and the axis along which to expand:

In [61]:
# expand dimensions
a = np.array([1,2,3])
print('Original:','\n','Shape',a.shape,'\n',a)


Original: 
 Shape (3,) 
 [1 2 3]


In [64]:
b = np.expand_dims(a,axis=0)
print('Expand along columns:','\n','Shape',b.shape,'\n')
b

Expand along columns: 
 Shape (1, 3) 



array([[1, 2, 3]])

In [65]:
c = np.expand_dims(a,axis=1)
print('Expand along rows:','\n','Shape',c.shape,'\n')
c

Expand along rows: 
 Shape (3, 1) 



array([[1],
       [2],
       [3]])

# Squeezing a NumPy array
On the other hand, if you instead want to reduce the axis of the array, use the `squeeze()` method. It removes the axis that has a single entry. This means if you have created a 2 x 2 x 1 matrix, squeeze() will remove the third dimension from the matrix:

In [68]:
# squeeze
a = np.array([[[1,2,3],
[4,5,6]]])

print('Original','\n','Shape',a.shape,'\n',a)


Original 
 Shape (1, 2, 3) 
 [[[1 2 3]
  [4 5 6]]]


In [67]:
b = np.squeeze(a, axis=0)
print('Squeeze array:','\n','Shape',b.shape,'\n',b)

Squeeze array: 
 Shape (2, 3) 
 [[1 2 3]
 [4 5 6]]


 However, if you already had a 2 x 2 matrix, using squeeze() in that case would give you an error:



In [71]:
# squeeze
a = np.array([[1,2,3],
[4,5,6]])
print('Original','\n','Shape',a.shape,'\n',a)


Original 
 Shape (2, 3) 
 [[1 2 3]
 [4 5 6]]


In [70]:
b = np.squeeze(a, axis=0)
print('Squeeze array:','\n','Shape',b.shape,'\n',b)

ValueError: cannot select an axis to squeeze out which has size not equal to one

# array conditions

In [79]:
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [82]:
### Some conditions very useful in Exploratory Data Analysis 
arr[arr<6]

array([1, 2, 3, 4, 5])